/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Interfaz extends javax.swing.JFrame {

    /* Constantes */
    private static final int A = 0;
    private static final int B = 1;
    private static final int C = 2;

    /* Opcion */
    private int OPCION_SELECCIONADA;

    /* Conclusion */
    Conclusion conclusionFinal;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        botonEmpezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        dialog.setTitle("Pregunta");
        dialog.setMinimumSize(new java.awt.Dimension(400, 150));

        botonA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonA.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Downloads\\save.png")); // NOI18N
        botonA.setText("A");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });

        botonB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Downloads\\save.png")); // NOI18N
        botonB.setText("B");
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });

        botonC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonC.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Downloads\\save.png")); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label.setText("¿Donde se encuentra el software?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonA)
                        .addGap(18, 18, 18)
                        .addComponent(botonB)
                        .addGap(18, 18, 18)
                        .addComponent(botonC)))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonA)
                    .addComponent(botonB)
                    .addComponent(botonC))
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 2");
        setResizable(false);

        botonEmpezar.setText("Empezar");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        jLabel1.setText("Un personaje X, necesita hallar el codigo de un");

        jLabel2.setText("software inteligente, para ello le entregan 3 unidades");

        jLabel3.setText("de almacenamiento y le indican que en solo una de");

        jLabel4.setText("ellas esta el codigo que requiere.");

        jLabel5.setText("El personaje X solo tiene una oportunidad de escoger");

        jLabel6.setText("y abrir una unidad de almacenamiento, cada unidad");

        jLabel7.setText("tiene una premisa.");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed

        // Habilitamos los botones
        this.botonA.setEnabled(true);
        this.botonB.setEnabled(true);
        this.botonC.setEnabled(true);

        // Elementos de resultado
        ArrayList<String[]> resultado;
        ArrayList<String[]> resultadoLimpio;

        // Opciones
        int[] opciones = new int[3];

        opciones[0] = Interfaz.A;
        opciones[1] = Interfaz.B;
        opciones[2] = Interfaz.C;

        // Seleccionamos la opcion
        Random random = new Random();
        int aleatorio = random.nextInt(3);

        this.OPCION_SELECCIONADA = opciones[aleatorio == 3 ? 2 : aleatorio];

        // Mostramos enunciado
        this.mostrarEnunciado();

        // Resolvemos las premisas
        resultado = this.generarResultado();
        resultadoLimpio = this.limpiarResultado(resultado);
        conclusionFinal = resolver(resultadoLimpio);

        // Mostramos la ventana
        dialog.setVisible(true);

        /*
        
        System.out.println("----------------------");

        for (String[] a : resultado) {
            System.out.println("A: " + a[0]);
            System.out.println("B: " + a[1]);
            System.out.println("C: " + a[2]);
        }

        System.out.println("----------------------");

        for (String[] b : resultadoLimpio) {
            System.out.println("A: " + b[0]);
            System.out.println("B: " + b[1]);
            System.out.println("C: " + b[2]);
        }

        System.out.println("----------------------");


        System.out.println("La premisa verdadera es: " + conclusion.getPremisa());
        System.out.println("El software se encuentra en la unidad: " + conclusion.getUbicacion());

        System.out.println("----------------------");
        
         */

    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed

        this.botonA.setEnabled(false);
        this.botonB.setEnabled(false);
        this.botonC.setEnabled(false);

        char boton = 'A';

        if (conclusionFinal.getUbicacion() == boton) {
            JOptionPane.showMessageDialog(null, "Acertaste", "Felicidades", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Fallaste", "Ups", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "El software se encuentra en la unidad " + conclusionFinal.getUbicacion(), "Solucion", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonAActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed

        this.botonA.setEnabled(false);
        this.botonB.setEnabled(false);
        this.botonC.setEnabled(false);

        char boton = 'B';

        if (conclusionFinal.getUbicacion() == boton) {
            JOptionPane.showMessageDialog(null, "Acertaste", "Felicidades", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Fallaste", "Ups", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "El software se encuentra en la unidad " + conclusionFinal.getUbicacion(), "Solucion", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonBActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed

        this.botonA.setEnabled(false);
        this.botonB.setEnabled(false);
        this.botonC.setEnabled(false);

        char boton = 'C';

        if (conclusionFinal.getUbicacion() == boton) {
            JOptionPane.showMessageDialog(null, "Acertaste", "Felicidades", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Fallaste", "Ups", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "El software se encuentra en la unidad " + conclusionFinal.getUbicacion(), "Solucion", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonCActionPerformed

    private ArrayList<String[]> generarResultado() {

        // Resultado
        ArrayList<String[]> resultado = new ArrayList<>();

        // Caminos
        boolean[][] caminos = new boolean[3][3];

        // Enunciados
        String P = construirEnunciadoUnidadA();
        String Q = construirEnunciadoUnidadB();
        String R = construirEnunciadoUnidadC();

        // Primer camino
        caminos[0][0] = true;
        caminos[0][1] = false;
        caminos[0][2] = false;

        // Segundo camino
        caminos[1][0] = false;
        caminos[1][1] = true;
        caminos[1][2] = false;

        // Tercer camino
        caminos[2][0] = false;
        caminos[2][1] = false;
        caminos[2][2] = true;

        // Recorremos cada camino
        for (int fila = 0; fila < 3; fila++) {

            String Ptemporal = P;
            String Qtemporal = Q;
            String Rtemporal = R;

            for (int columna = 0; columna < 3; columna++) {

                boolean subcamino = caminos[fila][columna];

                // Evaluamos enunciado P
                if (columna == 0) {

                    if (analizarEnunciado(P) == true) {

                        if (subcamino == false) {
                            Ptemporal = P.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Ptemporal = P.replace("no esta", "esta");
                        }

                    }

                }

                // Evaluamos enunciado Q
                if (columna == 1) {

                    if (analizarEnunciado(Q) == true) {

                        if (subcamino == false) {
                            Qtemporal = Q.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Qtemporal = Q.replace("no esta", "esta");
                        }

                    }

                }

                // Evaluamos enunciado R
                if (columna == 2) {

                    if (analizarEnunciado(R) == true) {

                        if (subcamino == false) {
                            Rtemporal = R.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Rtemporal = R.replace("no esta", "esta");
                        }

                    }

                }

            }

            // Agregamos premisas resultantes
            String[] premisa = new String[3];

            premisa[0] = Ptemporal;
            premisa[1] = Qtemporal;
            premisa[2] = Rtemporal;

            resultado.add(premisa);

        }

        return resultado;
    }

    private ArrayList<String[]> limpiarResultado(ArrayList<String[]> resultado) {

        ArrayList<String[]> resultadoLimpio = new ArrayList<>();

        for (String[] premisa : resultado) {

            int contador = 0;

            if (analizarEnunciado(premisa[0])) {
                contador++;
            }

            if (analizarEnunciado(premisa[1])) {
                contador++;
            }

            if (analizarEnunciado(premisa[2])) {
                contador++;
            }

            if (contador <= 1) {

                // Agregamos premisas que cumplen el requerimiento
                String[] premisaLimpia = new String[3];

                premisaLimpia[0] = premisa[0];
                premisaLimpia[1] = premisa[1];
                premisaLimpia[2] = premisa[2];

                resultadoLimpio.add(premisaLimpia);

            }

        }

        return resultadoLimpio;
    }

    private class Conclusion {

        private String premisa;
        private char ubicacion;

        public String getPremisa() {
            return premisa;
        }

        public void setPremisa(String premisa) {
            this.premisa = premisa;
        }

        public char getUbicacion() {
            return ubicacion;
        }

        public void setUbicacion(char ubicacion) {
            this.ubicacion = ubicacion;
        }

    }

    private Conclusion resolver(ArrayList<String[]> resultadoLimpio) {

        Conclusion conclusion = new Conclusion();

        boolean encontrado = false;
        int indice = 0;

        for (int i = 0; i < resultadoLimpio.size(); i++) {

            String[] premisa = resultadoLimpio.get(i);

            if (analizarEnunciado(premisa[0]) == false && premisa[0].contains("unidad")) {
                encontrado = true;
                indice = i;
                break;
            }

            if (analizarEnunciado(premisa[1]) == false && premisa[1].contains("unidad")) {
                encontrado = true;
                indice = i;
                break;
            }

            if (analizarEnunciado(premisa[2]) == false && premisa[2].contains("unidad")) {
                encontrado = true;
                indice = i;
                break;
            }

        }

        if (encontrado == true) {

            String[] premisa = resultadoLimpio.get(indice);

            // A
            if (analizarEnunciado(premisa[0])) {
                conclusion.setPremisa(premisa[0]);
                conclusion.setUbicacion('A');
            }

            // B
            if (analizarEnunciado(premisa[1])) {
                conclusion.setPremisa(premisa[1]);
                conclusion.setUbicacion('B');
            }

            // C
            if (analizarEnunciado(premisa[2])) {
                conclusion.setPremisa(premisa[2]);
                conclusion.setUbicacion('C');
            }

        }

        return conclusion;
    }

    private void mostrarEnunciado() {

        String enunciadoA = this.construirEnunciadoUnidadA();
        String enunciadoB = this.construirEnunciadoUnidadB();
        String enunciadoC = this.construirEnunciadoUnidadC();

        JOptionPane.showMessageDialog(null, "A: " + enunciadoA + "\n" + "B: " + enunciadoB + "\n" + "C: " + enunciadoC, "Enunciado", JOptionPane.INFORMATION_MESSAGE);

    }

    private String construirEnunciadoUnidadA() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado no esta aqui";
                break;

            case Interfaz.B:
                resultado = "El software buscado esta aqui";
                break;

            case Interfaz.C:
                resultado = "El software buscado no esta en la unidad B";
                break;
        }

        return resultado;
    }

    private String construirEnunciadoUnidadB() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado no esta en la unidad C";
                break;

            case Interfaz.B:
                resultado = "El software buscado no esta aqui";
                break;

            case Interfaz.C:
                resultado = "El software buscado esta aqui";
                break;
        }

        return resultado;
    }

    private String construirEnunciadoUnidadC() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado esta aqui";
                break;

            case Interfaz.B:
                resultado = "El software buscado no esta en la unidad A";
                break;

            case Interfaz.C:
                resultado = "El software buscado no esta aqui";
                break;
        }

        return resultado;
    }

    private boolean analizarEnunciado(String enunciado) {
        return !enunciado.contains("no esta");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JDialog dialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
