/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Window extends javax.swing.JFrame {

    /**
     * Dimensiones del tablero
     */
    public static final int ROWS = 3;
    public static final int COLUMNS = 3;

    /**
     * Tablero
     */
    public JButton[][] BOARD;

    /**
     * Estados del juego
     */
    public static final int WINNER_UNDEFINED = 0;
    public static final int WINNER_HUMAN = 1;
    public static final int WINNER_MACHINE = 2;

    /**
     * Creates new form Window
     */
    public Window() {

        /**
         * Inicializamos el tablero
         */
        BOARD = new JButton[ROWS][COLUMNS];

        /**
         * Inicializamos los componentes
         */
        initComponents();

        /**
         * Inicializamos las celdas del tablero
         */
        initBoard();

        /**
         * Dibujamos el tablero
         */
        draw();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 5");
        setResizable(false);

        panel.setLayout(new java.awt.GridLayout(3, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    private void initBoard() {

        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) {
                BOARD[row][column] = new JButton();
            }
        }

    }

    private void draw() {

        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) {

                JButton cell = BOARD[row][column];

                cell.setName(row + "" + column);
                cell.addActionListener((ActionEvent event) -> {
                    this.clickHandler(cell);
                });

                this.panel.add(cell);

            }
        }

    }

    private void clickHandler(JButton cell) {

        playHuman(cell);
        playMachine();

        switch (checkWinner()) {

            case WINNER_HUMAN:
                showMessageForHuman();
                break;

            case WINNER_MACHINE:
                showMessageForMachine();
                break;

        }

    }

    private void playHuman(JButton cell) {

        int row = Character.getNumericValue(cell.getName().charAt(0));
        int column = Character.getNumericValue(cell.getName().charAt(1));

        put("X", row, column);

    }

    private void playMachine() {

        Random random = new Random();
        ArrayList<JButton> freeCells = this.getFreeCells();

        if (freeCells.size() > 0) {

            JButton cell = freeCells.get(random.nextInt(freeCells.size()));

            int row = Character.getNumericValue(cell.getName().charAt(0));
            int column = Character.getNumericValue(cell.getName().charAt(1));

            put("O", row, column);

        }

    }

    private void put(String element, int row, int column) {
        BOARD[row][column].setText(element);
        BOARD[row][column].setEnabled(false);
    }

    public ArrayList<JButton> getFreeCells() {

        ArrayList<JButton> freeCells = new ArrayList<>();

        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) {

                JButton cell = BOARD[row][column];

                if (cell.isEnabled()) {
                    freeCells.add(cell);
                }

            }
        }

        return freeCells;
    }

    private int checkWinner() {

        JButton[][] pathList = {
            {BOARD[0][0], BOARD[0][1], BOARD[0][2]},
            {BOARD[1][0], BOARD[1][1], BOARD[1][2]},
            {BOARD[2][0], BOARD[2][1], BOARD[2][2]},
            {BOARD[0][0], BOARD[1][0], BOARD[2][0]},
            {BOARD[0][1], BOARD[1][1], BOARD[2][1]},
            {BOARD[0][2], BOARD[1][2], BOARD[2][2]},
            {BOARD[0][0], BOARD[1][1], BOARD[2][2]},
            {BOARD[0][2], BOARD[1][1], BOARD[2][0]}
        };

        for (JButton[] path : pathList) {

            String result = path[0].getText() + path[1].getText() + path[2].getText();

            if (result.equals("XXX")) {
                return WINNER_HUMAN;
            }

            if (result.equals("OOO")) {
                return WINNER_MACHINE;
            }

        }

        return WINNER_UNDEFINED;
    }

    private void showMessageForHuman() {
        JOptionPane.showMessageDialog(null, "¡Has ganado!", "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showMessageForMachine() {
        JOptionPane.showMessageDialog(null, "¡Ha ganado la maquina!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
