/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Cantidad de intentos
     */
    public static final int MAX_ATTEMPTS = 5;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Presiona el boton \"Iniciar\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed

        /**
         * Numero pensado
         */
        int number = (int) (Math.random() * 99);

        /**
         * Bandera de aprobacion
         */
        boolean approved = false;

        /**
         * Contador de intentos
         */
        int counter;

        /**
         * Respuesta proporcionada
         */
        String answer;

        /**
         * Mensaje inicial
         */
        JOptionPane.showMessageDialog(this, "A continuacion tendras " + MAX_ATTEMPTS + " intentos.", "¡Antes de empezar!", JOptionPane.INFORMATION_MESSAGE);

        /**
         * Depuracion
         */
        System.out.println("Numero: " + number);

        for (counter = 0; counter < MAX_ATTEMPTS; counter = counter + 1) {

            /**
             * Solicitamos la respuesta
             */
            answer = JOptionPane.showInputDialog(this, "¿Que numero he pensado?", "Intento #" + (counter + 1), JOptionPane.QUESTION_MESSAGE);

            /**
             * Validacion: Respuesta nula
             */
            if (answer != null) {

                try {

                    /**
                     * Validacion: Respuesta correcta
                     */
                    if (Integer.parseInt(answer) == number) {
                        JOptionPane.showMessageDialog(this, "Lo has logrado", "¡Felicitaciones!", JOptionPane.INFORMATION_MESSAGE);
                        approved = true;
                        break;
                    }

                    /**
                     * Validacion: Respuesta menor
                     */
                    if (Integer.parseInt(answer) < number) {
                        JOptionPane.showMessageDialog(this, "He pensado un numero mayor", "¡Oups!", JOptionPane.ERROR_MESSAGE);
                    }

                    /**
                     * Validacion: Respuesta mayor
                     */
                    if (Integer.parseInt(answer) > number) {
                        JOptionPane.showMessageDialog(this, "He pensado un numero menor", "¡Oups!", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (NumberFormatException e) {

                    /**
                     * Validacion: Respuesta numerica
                     */
                    JOptionPane.showMessageDialog(this, "Lo siento, ese numero no es valido", "¡Oups!", JOptionPane.ERROR_MESSAGE);
                    counter = counter - 1;

                }

            } else {

                /**
                 * Mensaje de rendicion
                 */
                if (JOptionPane.showConfirmDialog(this, "¿Tan rapido te rindes?", "¿En serio?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    break;
                } else {
                    counter = counter - 1;
                }

            }

        }

        /**
         * Mensaje de resultado
         */
        if (approved) {

            switch (counter) {

                /**
                 * Intento #1
                 */
                case 0:
                    JOptionPane.showMessageDialog(this, "¡Lo has conseguido, eres una leyenda en el arte de la adivinacion!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    break;

                /**
                 * Intento #2
                 */
                case 1:
                    JOptionPane.showMessageDialog(this, "¡Lo has conseguido, eres un maestro en el arte de la adivinacion!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    break;

                /**
                 * Intento #3
                 */
                case 2:
                    JOptionPane.showMessageDialog(this, "¡Lo has conseguido, eres un experto en el arte de la adivinacion!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    break;

                /**
                 * Intento #4
                 */
                case 3:
                    JOptionPane.showMessageDialog(this, "¡Lo has conseguido, eres un principiante en el arte de la adivinacion!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    break;

                /**
                 * Intento #5
                 */
                case 4:
                    JOptionPane.showMessageDialog(this, "¡Lo has conseguido, eres un aprendiz en el arte de la adivinacion!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    break;

            }

        } else {
            JOptionPane.showMessageDialog(this, "¡Suerte para la proxima!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
