/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Ivan
 */
public class Interfaz extends javax.swing.JFrame {

    /* Constantes */
    private static final int A = 0;
    private static final int B = 1;
    private static final int C = 2;

    /* Opcion */
    private int OPCION_SELECCIONADA;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botonEmpezar = new javax.swing.JButton();
        opcionA = new javax.swing.JRadioButton();
        opcionB = new javax.swing.JRadioButton();
        opcionC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 2");
        setResizable(false);

        botonEmpezar.setText("Empezar");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        buttonGroup.add(opcionA);
        opcionA.setText("Unidad A");

        buttonGroup.add(opcionB);
        opcionB.setSelected(true);
        opcionB.setText("Unidad B");

        buttonGroup.add(opcionC);
        opcionC.setText("Unidad C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opcionB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(botonEmpezar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcionC)
                            .addComponent(opcionA))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionA)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionB)
                    .addComponent(botonEmpezar))
                .addGap(18, 18, 18)
                .addComponent(opcionC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed

        ArrayList<String[]> resultado;
        ArrayList<String[]> resultadoLimpio;

        JRadioButton opciones[] = new JRadioButton[3];

        opciones[0] = this.opcionA;
        opciones[1] = this.opcionB;
        opciones[2] = this.opcionC;

        for (JRadioButton opcion : opciones) {

            if (opcion.isSelected()) {

                switch (opcion.getText().charAt(7)) {

                    case 'A':
                        this.OPCION_SELECCIONADA = Interfaz.A;
                        break;

                    case 'B':
                        this.OPCION_SELECCIONADA = Interfaz.B;
                        break;

                    case 'C':
                        this.OPCION_SELECCIONADA = Interfaz.C;
                        break;

                }

            }

        }

        this.mostrarEnunciado();
        resultado = this.resolver();
        resultadoLimpio = this.limpiarResultado(resultado);

        for (String[] a : resultado) {
            System.out.println(a[0]);
            System.out.println(a[1]);
            System.out.println(a[2]);
        }

        System.out.println("----------------------");

        for (String[] b : resultadoLimpio) {
            System.out.println(b[0]);
            System.out.println(b[1]);
            System.out.println(b[2]);
        }

    }//GEN-LAST:event_botonEmpezarActionPerformed

    private ArrayList<String[]> resolver() {

        // Resultado
        ArrayList<String[]> resultado = new ArrayList<>();

        // Caminos
        boolean[][] caminos = new boolean[3][3];

        // Enunciados
        String P = construirEnunciadoUnidadA();
        String Q = construirEnunciadoUnidadB();
        String R = construirEnunciadoUnidadC();

        // Primer camino
        caminos[0][0] = true;
        caminos[0][1] = false;
        caminos[0][2] = false;

        // Segundo camino
        caminos[1][0] = false;
        caminos[1][1] = true;
        caminos[1][2] = false;

        // Tercer camino
        caminos[2][0] = false;
        caminos[2][1] = false;
        caminos[2][2] = true;

        // Recorremos cada camino
        for (int fila = 0; fila < 3; fila++) {

            String Ptemporal = P;
            String Qtemporal = Q;
            String Rtemporal = R;

            for (int columna = 0; columna < 3; columna++) {

                boolean subcamino = caminos[fila][columna];

                // Evaluamos enunciado P
                if (columna == 0) {

                    if (analizarEnunciado(P) == true) {

                        if (subcamino == false) {
                            Ptemporal = P.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Ptemporal = P.replace("no esta", "esta");
                        }

                    }

                }

                // Evaluamos enunciado Q
                if (columna == 1) {

                    if (analizarEnunciado(Q) == true) {

                        if (subcamino == false) {
                            Qtemporal = Q.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Qtemporal = Q.replace("no esta", "esta");
                        }

                    }

                }

                // Evaluamos enunciado R
                if (columna == 2) {

                    if (analizarEnunciado(R) == true) {

                        if (subcamino == false) {
                            Rtemporal = R.replace("esta", "no esta");
                        }

                    } else {

                        if (subcamino == false) {
                            Rtemporal = R.replace("no esta", "esta");
                        }

                    }

                }

            }

            // Agregamos premisas resultantes
            String[] premisa = new String[3];

            premisa[0] = Ptemporal;
            premisa[1] = Qtemporal;
            premisa[2] = Rtemporal;

            resultado.add(premisa);

        }

        return resultado;
    }

    private ArrayList<String[]> limpiarResultado(ArrayList<String[]> resultado) {

        ArrayList<String[]> resultadoLimpio = new ArrayList<>();

        for (String[] premisa : resultado) {

            int contador = 0;

            if (analizarEnunciado(premisa[0])) {
                contador++;
            }

            if (analizarEnunciado(premisa[1])) {
                contador++;
            }

            if (analizarEnunciado(premisa[2])) {
                contador++;
            }

            if (contador <= 1) {

                // Agregamos premisas que cumplen el requerimiento
                String[] premisaLimpia = new String[3];

                premisaLimpia[0] = premisa[0];
                premisaLimpia[1] = premisa[1];
                premisaLimpia[2] = premisa[2];

                resultadoLimpio.add(premisaLimpia);

            }

        }

        return resultadoLimpio;
    }

    private void mostrarEnunciado() {

        String enunciadoA = this.construirEnunciadoUnidadA();
        String enunciadoB = this.construirEnunciadoUnidadB();
        String enunciadoC = this.construirEnunciadoUnidadC();

        JOptionPane.showMessageDialog(null, "A: " + enunciadoA + "\n" + "B: " + enunciadoB + "\n" + "C: " + enunciadoC);

    }

    private String construirEnunciadoUnidadA() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado no esta aqui";
                break;

            case Interfaz.B:
                resultado = "El software buscado esta aqui";
                break;

            case Interfaz.C:
                resultado = "El software buscado no esta en la unidad B";
                break;
        }

        return resultado;
    }

    private String construirEnunciadoUnidadB() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado no esta en la unidad C";
                break;

            case Interfaz.B:
                resultado = "El software buscado no esta aqui";
                break;

            case Interfaz.C:
                resultado = "El software buscado esta aqui";
                break;
        }

        return resultado;
    }

    private String construirEnunciadoUnidadC() {

        String resultado = new String();

        switch (this.OPCION_SELECCIONADA) {

            case Interfaz.A:
                resultado = "El software buscado esta aqui";
                break;

            case Interfaz.B:
                resultado = "El software buscado no esta en la unidad A";
                break;

            case Interfaz.C:
                resultado = "El software buscado no esta aqui";
                break;
        }

        return resultado;
    }

    private boolean analizarEnunciado(String enunciado) {
        return !enunciado.contains("no esta");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpezar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opcionA;
    private javax.swing.JRadioButton opcionB;
    private javax.swing.JRadioButton opcionC;
    // End of variables declaration//GEN-END:variables
}
